import type { Metadata } from "next";
import { alegreya_sc, alegreya_sans } from "./fonts";
import "./globals.css";

const alegreyaSc = alegreya_sc;
const alegreyaSans = alegreya_sans;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${alegreyaSc.variable} ${alegreyaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
